#!/bin/bash

. ~/diary_conf

KEY=$1

if [[ $DIARY_DIR = "" ]]; then
  DIARY_DIR=~/diary/
fi

case $KEY in
  "") vim $DIARY_DIR$(date "+%Y/%m/%d.md") ;;
  "past") vim $DIARY_DIR$(date -v -$2 "+%Y/%m/%d.md") ;;
  "future") vim $DIARY_DIR$(date -v +$2 "+%Y/%m/%d.md") ;;
  "commit")
    message=`date "+%Y-%m-%d"`
    cd $DIARY_DIR
    git add -A
    git commit -m "$message" ;;
  "push")
    cd $DIARY_DIR
    git push origin master ;;
  "grep")
    cd $DIARY_DIR
    git grep "$2" ;;
  "open")
    if [ $# -ge 3 ];then
      vim $DIARY_DIR$2/$3/$4.md
    else
      vim $DIARY_DIR$2.md
    fi ;;
esac

exit 0
