#!/bin/bash

. ~/.diary_conf

KEY=$1

if [[ $DIARY_DIR = "" ]]; then
  DIARY_DIR=~/diary/
fi

if [[ $EDITOR = "" ]]; then
  EDITOR=vim
fi

case $KEY in
  "") $EDITOR $DIARY_DIR$(date "+%Y/%m/%d.md") ;;
  "past") $EDITOR $DIARY_DIR$(date -v -$2 "+%Y/%m/%d.md") ;;
  "future") $EDITOR $DIARY_DIR$(date -v +$2 "+%Y/%m/%d.md") ;;
  "todo") $EDITOR $DIARY_DIR$1.md ;;
  "commit")
    message=`date "+%Y-%m-%d"`
    cd $DIARY_DIR
    git add -A
    git commit -m "$message" ;;
  "push")
    cd $DIARY_DIR
    git push origin master ;;
  "grep")
    cd $DIARY_DIR
    git grep "$2" ;;
  "open")
    if [ $# -ge 3 ];then
      $EDITOR $DIARY_DIR$2/$3/$4.md
    else
      $EDITOR $DIARY_DIR$2.md
    fi ;;
esac

exit 0
